require("dotenv").config();
const express = require("express");
const cors = require("cors");
const nodemailer = require("nodemailer");

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors({
  origin: "*",
  methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
  allowedHeaders: ["Content-Type", "Authorization"],
}));
app.use(express.json());

// Nodemailer transporter (Zoho)
const transporter = nodemailer.createTransport({
  host: "smtp.zoho.in", // use smtp.zoho.com if outside India
  port: 465,
  secure: true,
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

// Verify transporter
transporter.verify((error, success) => {
  if (error) {
    console.error("SMTP Connection Error:", error);
  } else {
    console.log("✅ SMTP Server ready to send emails");
  }
});

// Root route
app.get("/", (req, res) => {
  res.send("🚀 Enquiry Form Backend is live!");
});

// Send Email
app.post("/send-email", async (req, res) => {
  try {
    const { name, email, purpose } = req.body;

    if (!name || !email || !purpose) {
      return res.status(400).json({ message: "Name, email, and purpose are required!" });
    }

    // Email to admin and CEO
    const ownerMailOptions = {
      from: process.env.EMAIL_USER,
      to: `${process.env.EMAIL_USER}, ${process.env.CEO_EMAIL}`,
      subject: "📩 New Brochure Download Request",
      html: `
        <div style="font-family: Arial, sans-serif; padding: 20px; background: #f4f4f4;">
          <div style="max-width:600px; margin:auto; background:#fff; padding:20px; border-radius:8px;">
            <h2 style="color:#007bff;">📩 New Brochure Request</h2>
            <p><strong>Name:</strong> ${name}</p>
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Purpose:</strong></p>
            <blockquote style="border-left:4px solid #007bff; padding-left:10px;">${purpose}</blockquote>
            <hr>
            <p style="font-size:12px; color:#555;">Automatically generated by your website</p>
          </div>
        </div>
      `
    };

    // Send email only to admin and CEO
    await transporter.sendMail(ownerMailOptions);

    res.status(200).json({ message: "Request sent successfully!" });
  } catch (error) {
    console.error("Email Error:", error);
    res.status(500).json({ message: "Failed to send request.", error: error.message });
  }
});

// Start server
app.listen(PORT, () => {
  console.log(`✅ Server running on port:${PORT}`);
});